### ISSUE TITLE
Context isn't detected

### ISSUE THREAD

**Issue by pm-ur** [nosarthur/gita#231]
Hi! Either I'm using it wrong or there is some issue with automatic context. Here is some output to demonstrate the issue I have:
```
D:\d\ws\as20>gita group
master:
  - repo1
  - repo2
  - repo3
  - repo4
  - repo5
  - repo6
  - repo7
  - repo8
  - repo9
  - repoA
  - repoB
  - repoC
as20:
  - as20\repoA

D:\d\ws\as20>gita ls repoA
D:\d\ws\master\repoA

D:\d\ws\as20>gita ls as20\repoA
D:\d\ws\as20\repoA

D:\d\ws\as20>gita context auto

D:\d\ws\as20>gita context
auto: none detected!

D:\d\ws\as20>cd repoA

D:\d\ws\as20\repoA>gita context
auto: none detected!

```

FYI: Although it shouldn't make a difference, but as20/repoA is a worktree of the original repoA

**Comment by nosarthur** [comment]
Your group doesn't have path associated with it. That's why it didn't work. For example, when I run `gita group`, I get

```
youtube: /Users/dzhou/Documents/youtube-channel
  - handouts
  - youtube-demos
  - youtube-doc
```
That group path helps to `auto`matically determine context.

When u add many repos recursively `gita add -a`, the path is automatically set. If you want to add group path retrospectively, `gita group add -p` should work

If all fails, just edit `~/.config/gita/groups.csv` (on linux) directly. For my previous example

```
youtube:handouts youtube-demos youtube-doc:/Users/dzhou/Documents/youtube-channel
```

**Comment by nosarthur** [comment]
I think this is not an issue; please feel free to reopen if you have further questions
