### ISSUE TITLE
Switch to click?

### ISSUE THREAD

**Issue by ri0t** [nosarthur/gita#48]
First: Nice tool! As owner of a framework coming with dozens of modules, i built my own tools ([`forage`](https://github.com/ri0t/forage/))  to do stuff on multiple folders already, but gita helps so much more with git repositories, thanks!

Now, i propose switching from `argparser` to the wonderful [`click` library](https://palletsprojects.com/p/click/), because i constantly need to hit up gita's documentation to remember what the symbols and colours on the `ll` command refer to. I wanted to add this to `ll`s help page, but i don't even know if this is possible with `argparse`. With `click`, you just add it to the commands docstring.

If you're open to this, i'd gladly contribute towards the switch.

**Comment by nosarthur** [comment]
Thanks for the suggestion. It makes a lot of sense to add description of the symbols and colors in 
```
gita ll -h
```

I am not familiar with `click` so not sure how much work it involves for the switch. `argparse` actually has a very easy way to add description to sub-command docstring. Take `gita ll` for example, if I add `description="hello", ` to

https://github.com/nosarthur/gita/blob/master/gita/__main__.py#L118

Then I get
```
chronos (master *) gita $ gita ll -h
usage: gita ll [-h]

hello

optional arguments:
  -h, --help  show this help message and exit
```

Please feel free to make a PR to add the symbol/color description. Otherwise I will probably add them sometime next week.
