### ISSUE TITLE
Error on `gita ll` after rename implemented

### ISSUE THREAD

**Issue by mortenfyhn** [nosarthur/gita#65]
Hi, I pulled master and rebuilt (`pip3 install -e <gita source dir>`), and I now get a ValueError when running `gita ll`:
```
Traceback (most recent call last):
  File "/home/morten/.local/bin/gita", line 11, in <module>
    load_entry_point('gita', 'console_scripts', 'gita')()
  File "/home/morten/workspace/gita/gita/__main__.py", line 128, in main
    choices=utils.get_repos(),
  File "/home/morten/workspace/gita/gita/utils.py", line 52, in get_repos
    path, name = d.split(',')
ValueError: not enough values to unpack (expected 2, got 1)
```

I ran a quick git bisect and 2684120 (add rename sub-command) seems to be the commit that introduced the error. I haven't investigated any further, just wanted to let you know.

**Comment by nosarthur** [comment]
Thanks @mortenfyhn Version 0.9.8 introduces a new format for the `repo_path` file. See

https://github.com/nosarthur/gita/releases/tag/v0.9.8

You can either change the file directly, or remove it, and add the repos again. 

Since it's still verion 0, I didn't make it backward compatible. Sorry for the inconvenience.

**Comment by mortenfyhn** [comment]
Got it!
